export const USER_DATA_LIST_FETCH = 'USER_DATA_LIST_FETCH'
export const USER_DATA_LIST_UPDATE = 'USER_DATA_LIST_UPDATE'
export const USER_DATA_LIST_FETCH_ERROR = 'USER_DATA_LIST_FETCH_ERROR'
export const ERROR_FETCHING_USERS = 'ERROR_FETCHING_USERS'
